<a href="https://colab.research.google.com/github/edgi-govdata-archiving/GHG-CDP/blob/main/GHGRP_geometry.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas
import geopandas

from google import colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
ghg_states = pandas.read_csv("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/Climate_Data_Project/web_data/aggregated_emissions_by_state_2023.csv")

In [ ]:
import requests
import zipfile
import io

url = "https://www2.census.gov/geo/tiger/TIGER2025/STATE/tl_2025_us_state.zip"

# Download
r = requests.get(url)

# Extract
with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    z.extractall("states_shapefile")

In [ ]:
states = geopandas.read_file("states_shapefile/tl_2025_us_state.shp")

In [ ]:
ghg_states

,Effective State,Year,Total Emissions,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,LDC - Direct Emissions,SF6 from Elec. Equip.,GHG Quantity Associated with Coal-based liquid fuel production,GHG Quantity Associated with Petroleum Products Produced,GHG Quantity Associated with Petroleum Products Imported,GHG Quantity Associated with Petroleum Products Exported,GHG Quantity Associated with Natural Gas Supply,GHG Quantity Associated with Natural Gas Liquids Supply,GHG Quantity Associated with CO2 Supply
0,AK,2023,3.441354e+07,1.958167e+07,1.483187e+07,1.421270e+07,1.556688e+06,3.802852e+06,0.00000,0.000,9427.0476,0,1.172975e+07,0,0.000000e+00,3102124.1,0.000000e+00,0.000000e+00
1,AL,2023,1.115240e+08,7.220382e+07,3.932015e+07,7.203031e+07,0.000000e+00,0.000000e+00,0.00000,171906.200,1605.4848,0,2.286587e+07,0,0.000000e+00,14725673.4,1.728606e+06,0.000000e+00
2,AR,2023,5.225602e+07,3.789141e+07,1.436461e+07,3.776511e+07,4.681646e+03,1.863942e+04,0.00000,102983.250,0.0000,0,1.214474e+07,0,0.000000e+00,2219863.6,0.000000e+00,0.000000e+00
3,AZ,2023,4.474022e+07,4.205184e+07,2.688377e+06,4.198509e+07,0.000000e+00,0.000000e+00,0.00000,22454.200,44300.3544,0,0.000000e+00,0,0.000000e+00,2688376.6,0.000000e+00,0.000000e+00
4,CA,2023,4.485830e+08,9.938718e+07,3.491958e+08,9.048345e+07,2.283489e+06,4.798612e+06,114021.45610,1618617.550,88985.0028,0,2.261681e+08,0,3.280144e+07,88075407.9,2.150874e+06,0.000000e+00
5,CO,2023,1.113933e+08,6.248199e+07,4.891135e+07,3.779897e+07,1.258182e+07,1.179256e+07,25237.40225,275563.050,7830.7740,0,9.808177e+06,0,0.000000e+00,22896307.7,1.084871e+06,1.512199e+07
6,CT,2023,3.373830e+07,1.106851e+07,2.266980e+07,1.088945e+07,0.000000e+00,0.000000e+00,0.00000,175740.496,3321.8232,0,0.000000e+00,0,1.585770e+07,6812094.0,0.000000e+00,0.000000e+00
7,DC,2023,2.793500e+05,2.793500e+05,0.000000e+00,2.793500e+05,0.000000e+00,0.000000e+00,0.00000,0.000,0.0000,0,0.000000e+00,0,0.000000e+00,0.0,0.000000e+00,0.000000e+00
8,DE,2023,2.605931e+07,5.816609e+06,2.024270e+07,5.794099e+06,0.000000e+00,0.000000e+00,0.00000,22509.600,0.0000,0,1.767532e+07,0,0.000000e+00,2567374.1,0.000000e+00,0.000000e+00
9,FL,2023,1.203074e+08,1.091669e+08,1.114044e+07,1.089102e+08,0.000000e+00,0.000000e+00,90453.60106,138575.294,27647.6220,0,0.000000e+00,0,0.000000e+00,11140444.1,0.000000e+00,0.000000e+00
10,GA,2023,6.990289e+07,5.511166e+07,1.479123e+07,5.479199e+07,0.000000e+00,0.000000e+00,115118.14790,177828.356,26719.7304,0,0.000000e+00,0,0.000000e+00,14791233.1,0.000000e+00,0.000000e+00
11,GU,2023,1.304859e+06,1.304859e+06,0.000000e+00,1.304859e+06,0.000000e+00,0.000000e+00,0.00000,0.000,0.0000,0,0.000000e+00,0,0.000000e+00,0.0,0.000000e+00,0.000000e+00
12,HI,2023,1.893156e+07,6.712637e+06,1.221893e+07,6.706243e+06,0.000000e+00,0.000000e+00,0.00000,0.000,6393.3708,0,1.205672e+07,0,0.000000e+00,162208.2,0.000000e+00,0.000000e+00
13,IA,2023,6.132755e+07,4.391131e+07,1.741625e+07,4.359202e+07,0.000000e+00,0.000000e+00,197585.23860,116413.948,5285.1312,0,0.000000e+00,0,0.000000e+00,17416245.1,0.000000e+00,0.000000e+00
14,ID,2023,1.035496e+07,5.703363e+06,4.651600e+06,5.668302e+06,0.000000e+00,0.000000e+00,0.00000,35060.500,0.0000,0,0.000000e+00,0,0.000000e+00,4651599.5,0.000000e+00,0.000000e+00
15,IL,2023,3.093643e+08,7.201652e+07,2.373478e+08,7.135507e+07,0.000000e+00,0.000000e+00,260958.23160,392881.856,7608.8388,0,1.512779e+08,0,3.677265e+07,42805938.5,6.491330e+06,0.000000e+00
16,IN,2023,2.461586e+08,1.086055e+08,1.375531e+08,1.079039e+08,0.000000e+00,0.000000e+00,0.00000,658350.162,43321.0716,0,7.058781e+07,0,3.653660e+04,66928768.5,0.000000e+00,0.000000e+00
17,KS,2023,1.336675e+08,3.281791e+07,1.008495e+08,3.243438e+07,0.000000e+00,2.252944e+05,33412.81684,59377.250,65439.3972,0,5.549816e+07,0,4.185914e+06,8531174.7,3.263429e+07,0.000000e+00
18,KY,2023,1.129854e+08,6.511821e+07,4.786715e+07,6.508278e+07,0.000000e+00,0.000000e+00,0.00000,24850.750,10577.6952,0,4.300137e+07,0,0.000000e+00,3720575.8,1.145209e+06,0.000000e+00
19,LA,2023,5.805961e+08,1.461318e+08,4.344643e+08,1.443185e+08,2.228378e+05,1.322529e+06,155919.13020,22112.850,89967.7968,0,3.964283e+08,0,0.000000e+00,1139278.0,3.689670e+07,0.000000e+00
20,MA,2023,2.441768e+07,9.341763e+06,1.507592e+07,8.812173e+06,0.000000e+00,0.000000e+00,0.00000,529589.720,0.0000,0,0.000000e+00,0,0.000000e+00,15075922.1,0.000000e+00,0.000000e+00
21,MD,2023,1.936671e+07,1.458785e+07,4.778860e+06,1.441474e+07,0.000000e+00,0.000000e+00,0.00000,173108.098,0.0000,0,0.000000e+00,0,0.000000e+00,4778860.2,0.000000e+00,0.000000e+00
22,ME,2023,3.634281e+06,3.421060e+06,2.132217e+05,3.421060e+06,0.000000e+00,0.000000e+00,0.00000,0.000,0.0000,0,0.000000e+00,0,0.000000e+00,213221.7,0.000000e+00,0.000000e+00
23,MI,2023,1.333004e+08,6.904408e+07,6.425630e+07,6.754527e+07,5.184518e+05,3.859504e+05,12216.35000,561597.686,20592.6864,0,2.191429e+07,0,0.000000e+00,42206436.4,1.355732e+05,0.000000e+00
24,MN,2023,1.250017e+08,3.476314e+07,9.023861e+07,3.446371e+07,0.000000e+00,0.000000e+00,1649.94566,147020.896,150761.2608,0,6.728766e+07,0,0.000000e+00,22950942.0,0.000000e+00,0.000000e+00
25,MO,2023,7.085376e+07,5.967095e+07,1.118281e+07,5.952679e+07,0.000000e+00,0.000000e+00,0.00000,135746.850,8410.0308,0,0.000000e+00,0,0.000000e+00,11182810.7,0.000000e+00,0.000000e+00
26,MS,2023,1.051032e+08,4.183725e+07,6.326599e+07,4.163684e+07,1.288454e+05,6.690351e+04,1637.51640,3021.100,0.0000,0,5.431810e+07,0,0.000000e+00,351674.8,0.000000e+00,8.596215e+06
27,MT,2023,5.512891e+07,1.810843e+07,3.702048e+07,1.800748e+07,6.349924e+04,0.000000e+00,0.00000,37452.350,0.0000,0,3.063895e+07,0,1.213975e+05,5890628.4,3.695043e+05,0.000000e+00
28,NC,2023,8.622198e+07,4.465803e+07,4.156395e+07,4.427108e+07,0.000000e+00,0.000000e+00,0.00000,243610.442,143337.4668,0,0.000000e+00,0,0.000000e+00,41563953.0,0.000000e+00,0.000000e+00
29,ND,2023,6.104055e+07,3.727079e+07,2.376975e+07,3.449306e+07,2.398894e+06,3.399488e+05,0.00000,0.000,38895.7740,351488,9.980877e+06,0,0.000000e+00,3376287.0,1.006110e+07,0.000000e+00
30,NE,2023,3.160316e+07,2.571258e+07,5.890583e+06,2.562650e+07,0.000000e+00,0.000000e+00,0.00000,81121.200,4963.0812,0,0.000000e+00,0,0.000000e+00,5890582.8,0.000000e+00,0.000000e+00
31,NH,2023,3.239226e+06,2.392513e+06,8.467129e+05,2.392513e+06,0.000000e+00,0.000000e+00,0.00000,0.000,0.0000,0,0.000000e+00,0,0.000000e+00,846712.9,0.000000e+00,0.000000e+00
32,NJ,2023,8.890793e+07,1.992798e+07,6.897995e+07,1.935213e+07,0.000000e+00,0.000000e+00,0.00000,575849.136,0.0000,0,4.121460e+07,0,1.255646e+06,26509709.0,0.000000e+00,0.000000e+00
33,NM,2023,4.310050e+07,2.374888e+07,1.935162e+07,2.088914e+07,1.632414e+06,1.145579e+06,4287.01642,57252.150,20208.3696,0,1.107011e+07,0,0.000000e+00,5169544.4,0.000000e+00,3.111971e+06
34,NV,2023,2.894426e+07,1.578549e+07,1.315878e+07,1.559527e+07,0.000000e+00,0.000000e+00,0.00000,158818.450,31396.0332,0,1.987604e+05,0,0.000000e+00,12960015.6,0.000000e+00,0.000000e+00
35,NY,2023,1.114375e+08,3.809004e+07,7.334745e+07,3.637945e+07,2.912835e+05,3.278821e+05,0.00000,981236.040,110185.1724,0,0.000000e+00,0,1.477438e+07,58573069.4,0.000000e+00,0.000000e+00
36,OH,2023,2.616473e+08,1.021494e+08,1.594979e+08,9.980041e+07,7.858216e+05,5.765876e+05,46917.18314,659376.596,280255.1604,0,6.683530e+07,0,3.582649e+07,24024749.8,3.281139e+07,0.000000e+00
37,OK,2023,1.489986e+08,7.004356e+07,7.895507e+07,4.800908e+07,1.272466e+07,9.113786e+06,11576.86034,155077.700,29374.7220,0,6.805593e+07,0,0.000000e+00,10899134.7,0.000000e+00,0.000000e+00
38,OR,2023,2.046088e+07,1.380737e+07,6.653514e+06,1.373457e+07,0.000000e+00,0.000000e+00,0.00000,67024.200,5776.9728,0,0.000000e+00,0,0.000000e+00,6653513.8,0.000000e+00,0.000000e+00
39,PA,2023,1.923981e+08,1.093015e+08,8.309659e+07,1.027332e+08,1.733628e+06,3.871956e+06,176655.56530,782338.842,3764.4396,0,3.595539e+07,0,8.644564e+04,35741426.0,1.131332e+07,0.000000e+00
40,PR,2023,1.380342e+07,1.380342e+07,0.000000e+00,1.372998e+07,0.000000e+00,0.000000e+00,0.00000,0.000,73437.8196,0,0.000000e+00,0,0.000000e+00,0.0,0.000000e+00,0.000000e+00
41,RI,2023,6.302930e+06,4.238400e+06,2.064530e+06,4.117039e+06,0.000000e+00,0.000000e+00,0.00000,121360.600,0.0000,0,0.000000e+00,0,0.000000e+00,2064530.0,0.000000e+00,0.000000e+00
42,SC,2023,4.038538e+07,3.520745e+07,5.177933e+06,3.513688e+07,0.000000e+00,0.000000e+00,0.00000,49735.050,20831.6760,0,0.000000e+00,0,0.000000e+00,5177933.0,0.000000e+00,0.000000e+00
43,SD,2023,6.551820e+06,6.299962e+06,2.518573e+05,6.299962e+06,0.000000e+00,0.000000e+00,0.00000,0.000,0.0000,0,0.000000e+00,0,0.000000e+00,251857.3,0.000000e+00,0.000000e+00
44,TN,2023,7.411300e+07,3.740961e+07,3.670339e+07,3.726503e+07,0.000000e+00,0.000000e+00,2109.66367,61234.600,81235.8072,0,2.359090e+07,0,3.519494e+06,9592994.1,0.000000e+00,0.000000e+00
45,TX,2023,2.456705e+09,4.848140e+08,1.971891e+09,3.798493e+08,5.330236e+07,5.027031e+07,205164.69600,979329.900,207571.9296,0,8.515487e+08,0,6.990682e+08,40393386.6,3.808802e+08,0.000000e+00
46,UT,2023,7.393837e+07,2.938689e+07,4.455148e+07,2.827607e+07,6.388840e+05,2.943646e+05,0.00000,100105.498,77465.2572,0,3.167256e+07,0,0.000000e+00,12111867.8,7.670499e+05,0.000000e+00
47,VA,2023,5.233045e+07,3.506543e+07,1.726502e+07,3.467112e+07,0.000000e+00,0.000000e+00,34282.59563,247602.854,112426.7772,0,0.000000e+00,0,0.000000e+00,17265022.1,0.000000e+00,0.000000e+00
48,VI,2023,5.811637e+05,5.811637e+05,0.000000e+00,5.811637e+05,0.000000e+00,0.000000e+00,0.00000,0.000,0.0000,0,0.000000e+00,0,0.000000e+00,0.0,0.000000e+00,0.000000e+00
49,VT,2023,9.915503e+05,2.932633e+05,6.982870e+05,2.888251e+05,0.000000e+00,0.000000e+00,0.00000,4100.900,337.2576,0,0.000000e+00,0,0.000000e+00,698287.0,0.000000e+00,0.000000e+00
50,WA,2023,1.303489e+08,2.442333e+07,1.059256e+08,2.424587e+07,0.000000e+00,0.000000e+00,0.00000,110945.034,66512.2740,0,8.465189e+07,0,3.713117e+06,17560594.4,0.000000e+00,0.000000e+00
51,WI,2023,7.171022e+07,3.951643e+07,3.219379e+07,3.935463e+07,0.000000e+00,0.000000e+00,0.00000,161804.498,0.0000,0,3.300279e+06,0,0.000000e+00,28893506.4,0.000000e+00,0.000000e+00
52,WV,2023,8.511679e+07,6.569926e+07,1.941754e+07,6.455894e+07,3.903920e+05,5.123423e+05,42427.95000,195151.450,0.0000,0,2.885782e+06,0,0.000000e+00,4738730.7,1.178472e+07,8.302900e+03
53,WY,2023,7.368554e+07,5.084743e+07,2.283810e+07,5.005446e+07,1.417955e+05,6.511709e+05,0.00000,0.000,0.0000,0,1.938577e+07,0,0.000000e+00,1759704.1,1.692628e+06,0.000000e+00

In [ ]:
states

,REGION,DIVISION,STATEFP,STATENS,GEOID,GEOIDFQ,STUSPS,NAME,LSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,1,2,36,01779796,36,0400000US36,NY,New York,00,G4000,A,122049344560,19256566831,+42.9133974,-075.5962723,"MULTIPOLYGON (((-74.72623 44.99486, -74.72257 ..."
1,4,8,32,01779793,32,0400000US32,NV,Nevada,00,G4000,A,284537074263,1839852286,+39.3310928,-116.6151469,"POLYGON ((-119.32418 41.99392, -119.32362 41.9..."
2,4,9,02,01785533,02,0400000US02,AK,Alaska,00,G4000,A,1479893380150,244326118163,+63.3473560,-152.8397334,"MULTIPOLYGON (((-167.55823 60.22436, -167.5567..."
3,9,0,60,01802701,60,0400000US60,AS,American Samoa,00,G4000,A,197759070,1307243751,-14.2668475,-170.6671854,"MULTIPOLYGON (((-168.22527 -14.53591, -168.224..."
4,1,1,50,01779802,50,0400000US50,VT,Vermont,00,G4000,A,23872664356,1030573104,+44.0589536,-072.6710173,"POLYGON ((-72.04187 44.15665, -72.0418 44.1566..."
5,1,1,09,01779780,09,0400000US09,CT,Connecticut,00,G4000,A,12542101087,1816013585,+41.5798637,-072.7466572,"POLYGON ((-72.5279 41.17777, -72.55156 41.1732..."
6,3,5,10,01779781,10,0400000US10,DE,Delaware,00,G4000,A,5046707808,1399203452,+38.9985661,-075.4416440,"POLYGON ((-75.50949 39.68652, -75.50942 39.686..."
7,4,8,35,00897535,35,0400000US35,NM,New Mexico,00,G4000,A,314198529853,726526491,+34.4346844,-106.1316180,"POLYGON ((-103.06472 32.33465, -103.0647 32.33..."
8,3,5,37,01027616,37,0400000US37,NC,North Carolina,00,G4000,A,125935547374,13453873497,+35.5397100,-079.1308636,"POLYGON ((-77.89977 36.5446, -77.89942 36.5446..."
9,2,3,55,01779806,55,0400000US55,WI,Wisconsin,00,G4000,A,140295112685,29340578971,+44.6309071,-089.7093916,"POLYGON ((-89.55482 46.2279, -89.5548 46.2279,..."
10,4,9,41,01155107,41,0400000US41,OR,Oregon,00,G4000,A,248630742196,6168664862,+43.9717125,-120.6229578,"POLYGON ((-121.44123 45.69728, -121.42442 45.6..."
11,2,4,31,01779792,31,0400000US31,NE,Nebraska,00,G4000,A,198950563271,1378346850,+41.5433050,-099.8118641,"POLYGON ((-95.93779 41.39075, -95.93742 41.389..."
12,3,5,13,01705317,13,0400000US13,GA,Georgia,00,G4000,A,149487720450,4417264043,+32.6295789,-083.4235109,"POLYGON ((-81.09538 31.52098, -81.0971 31.5197..."
13,3,6,01,01779775,01,0400000US01,AL,Alabama,00,G4000,A,131186429591,4580729056,+32.7395785,-086.8434469,"POLYGON ((-85.12733 31.76256, -85.12753 31.762..."
14,4,8,49,01455989,49,0400000US49,UT,Utah,00,G4000,A,213921693698,5963352640,+39.3349925,-111.6563326,"POLYGON ((-111.50781 41.99955, -111.50727 41.9..."
15,2,3,39,01085497,39,0400000US39,OH,Ohio,00,G4000,A,105824499476,10273857263,+40.4149297,-082.7119975,"POLYGON ((-80.51915 40.90033, -80.51914 40.899..."
16,3,7,40,01102857,40,0400000US40,OK,Oklahoma,00,G4000,A,177664943367,3372936372,+35.5900815,-097.4867789,"POLYGON ((-95.78676 36.99931, -95.78601 36.999..."
17,3,6,47,01325873,47,0400000US47,TN,Tennessee,00,G4000,A,106771660995,2344243062,+35.8584600,-086.3496339,"POLYGON ((-83.98762 36.58947, -83.98724 36.589..."
18,4,8,56,01779807,56,0400000US56,WY,Wyoming,00,G4000,A,251458188895,1868027102,+42.9896591,-107.5443922,"POLYGON ((-106.32116 40.99912, -106.32621 40.9..."
19,1,1,25,00606926,25,0400000US25,MA,Massachusetts,00,G4000,A,20204475228,7130575380,+42.1565196,-071.4895915,"POLYGON ((-71.25515 42.73655, -71.2551 42.7365..."
20,3,5,51,01779803,51,0400000US51,VA,Virginia,00,G4000,A,102256455003,8529795937,+37.5222512,-078.6681938,"POLYGON ((-76.9159 36.55215, -76.9162 36.55181..."
21,3,5,11,01702382,11,0400000US11,DC,District of Columbia,00,G4000,A,158318961,18706999,+38.9042429,-077.0165243,"POLYGON ((-77.11975 38.93435, -77.11886 38.935..."
22,2,4,19,01779785,19,0400000US19,IA,Iowa,00,G4000,A,144660389024,1085298995,+42.0700227,-093.4933492,"POLYGON ((-95.86095 43.50004, -95.85979 43.500..."
23,4,8,04,01779777,04,0400000US04,AZ,Arizona,00,G4000,A,294366238828,853868947,+34.2039362,-111.6063449,"POLYGON ((-110.75069 37.00301, -110.74193 37.0..."
24,3,7,48,01779801,48,0400000US48,TX,Texas,00,G4000,A,676660157338,19008164905,+31.4347032,-099.2818238,"POLYGON ((-98.42353 34.08284, -98.42235 34.082..."
25,4,9,15,01779782,15,0400000US15,HI,Hawaii,00,G4000,A,16634436568,11777362694,+19.8281671,-155.4950421,"MULTIPOLYGON (((-178.44359 28.41899, -178.4383..."
26,2,4,38,01779797,38,0400000US38,ND,North Dakota,00,G4000,A,178694402328,4414688315,+47.4421740,-100.4608258,"POLYGON ((-98.99982 48.99996, -98.93769 49.000..."
27,3,6,21,01779786,21,0400000US21,KY,Kentucky,00,G4000,A,102267794436,2383097595,+37.5336844,-085.2929801,"MULTIPOLYGON (((-89.5712 36.55214, -89.57114 3..."
28,9,0,78,01802710,78,0400000US78,VI,United States Virgin Islands,00,G4000,A,348021915,1550236186,+18.3392359,-064.9500433,"MULTIPOLYGON (((-64.76834 18.26033, -64.77074 ..."
29,3,5,54,01779805,54,0400000US54,WV,West Virginia,00,G4000,A,62266655298,488773392,+38.6472854,-080.6183274,"POLYGON ((-77.75438 39.33346, -77.75422 39.333..."
30,3,5,12,00294478,12,0400000US12,FL,Florida,00,G4000,A,138973813223,45960479273,+28.3989775,-082.5143005,"MULTIPOLYGON (((-80.18387 25.34818, -80.18389 ..."
31,2,3,17,01779784,17,0400000US17,IL,Illinois,00,G4000,A,143779367883,6215353468,+40.1028754,-089.1526108,"POLYGON ((-87.89243 38.28285, -87.89334 38.282..."
32,2,4,27,00662849,27,0400000US27,MN,Minnesota,00,G4000,A,206245435043,18936592419,+46.3159573,-094.1996043,"POLYGON ((-95.31991 48.99892, -95.31778 48.998..."
33,3,5,24,01714934,24,0400000US24,MD,Maryland,00,G4000,A,25151298706,6979771758,+38.9466584,-076.6744939,"POLYGON ((-75.756 39.24607, -75.75578 39.24334..."
34,1,1,44,01219835,44,0400000US44,RI,Rhode Island,00,G4000,A,2677770297,1323680040,+41.5964850,-071.5264901,"MULTIPOLYGON (((-71.20837 41.6906, -71.20829 4..."
35,4,8,16,01779783,16,0400000US16,ID,Idaho,00,G4000,A,214050683201,2390817981,+44.3484220,-114.5588540,"POLYGON ((-116.35844 49.00047, -116.34805 49.0..."
36,1,1,33,01779794,33,0400000US33,NH,New Hampshire,00,G4000,A,23190733491,1025349624,+43.6727945,-071.5841886,"POLYGON ((-70.83887 43.24449, -70.83886 43.244..."
37,4,9,06,01779778,06,0400000US06,CA,California,00,G4000,A,403676564152,20288505023,+37.1551773,-119.5434183,"MULTIPOLYGON (((-119.99987 41.18397, -119.9998..."
38,1,2,34,01779795,34,0400000US34,NJ,New Jersey,00,G4000,A,19049443028,3533161265,+40.1072744,-074.6652012,"POLYGON ((-74.46493 39.29823, -74.46906 39.294..."
39,3,5,45,01779799,45,0400000US45,SC,South Carolina,00,G4000,A,77865991519,5074452542,+33.8741776,-080.8542639,"POLYGON ((-81.3666 35.16488, -81.35786 35.1644..."
40,2,3,26,01779789,26,0400000US26,MI,Michigan,00,G4000,A,146625947203,103860207077,+44.8441768,-085.6604907,"POLYGON ((-87.1127 47.818, -87.0631 47.79999, ..."
41,3,7,05,00068085,05,0400000US05,AR,Arkansas,00,G4000,A,134658642291,3122591253,+34.8955256,-092.4446262,"POLYGON ((-90.95577 34.11871, -90.95451 34.117..."
42,3,6,28,01779790,28,0400000US28,MS,Mississippi,00,G4000,A,121534611855,3914024462,+32.6864714,-089.6561377,"POLYGON ((-88.43138 32.22767, -88.4318 32.2243..."
43,2,4,29,01779791,29,0400000US29,MO,Missouri,00,G4000,A,178052192662,2487934091,+38.3507508,-092.4567820,"POLYGON ((-93.37439 40.58033, -93.37429 40.580..."
44,4,8,30,00767982,30,0400000US30,MT,Montana,00,G4000,A,376973522036,3866841435,+47.0511770,-109.6348174,"POLYGON ((-105.05764 48.99923, -105.0341 48.99..."
45,2,4,20,00481813,20,0400000US20,KS,Kansas,00,G4000,A,211754288230,1345197050,+38.4985464,-098.3834298,"POLYGON ((-94.61764 37.76124, -94.61766 37.760..."
46,2,3,18,00448508,18,0400000US18,IN,Indiana,00,G4000,A,92786782808,1543815569,+39.9013136,-086.2919129,"POLYGON ((-86.3296 38.1818, -86.33037 38.1821,..."
47,9,0,72,01779808,72,0400000US72,PR,Puerto Rico,00,G4000,A,8869703179,4921575413,+18.2176480,-066.4107992,"MULTIPOLYGON (((-67.99869 18.17076, -67.99869 ..."
48,2,4,46,01785534,46,0400000US46,SD,South Dakota,00,G4000,A,196341986509,3387247814,+44.4467957,-100.2381762,"POLYGON ((-98.72438 45.93873, -98.72425 45.938..."
49,4,8,08,01779779,08,0400000US08,CO,Colorado,00,G4000,A,268419398775,1185110804,+38.9937669,-105.5087122,"POLYGON ((-105.15504 36.99526, -105.15543 36.9..."
50,1,2,42,01779798,42,0400000US42,PA,Pennsylvania,00,G4000,A,115882017582,3397072484,+40.9046042,-077.8275233,"POLYGON ((-75.5931 39.83772, -75.59319 39.8377..."
51,4,9,53,01779804,53,0400000US53,WA,Washington,00,G4000,A,172121688057,12545987222,+47.4073238,-120.5757999,"POLYGON ((-118.40382 46.00077, -118.40506 46.0..."
52,3,7,22,01629543,22,0400000US22,LA,Louisiana,00,G4000,A,111927154861,23724485446,+30.7083190,-091.6046207,"POLYGON ((-92.72474 33.01439, -92.72365 33.014..."
53,9,0,69,01779809,69,0400000US69,MP,Commonwealth of the Northern Mariana Islands,00,G4000,A,472292520,4644252457,+15.0010865,+145.6181702,"MULTIPOLYGON (((145.05897 14.125, 145.06302 14..."
54,9,0,66,01802705,66,0400000US66,GU,Guam,00,G4000,A,543555846,934337452,+13.4382885,+144.7729494,"POLYGON ((144.56343 13.44806, 144.56357 13.450..."
55,1,1,23,01779787,23,0400000US23,ME,Maine,00,G4000,A,79888899089,11744562992,+45.4092843,-068.6666160,"POLYGON ((-67.80569 45.68005, -67.80363 45.677..."

In [ ]:
ghgstates_geo = pandas.merge(ghg_states, states, left_on="Effective State", right_on="STUSPS")

In [ ]:
ghgstates_geo = geopandas.GeoDataFrame(ghgstates_geo, geometry = "geometry")

In [ ]:
ghgstates_geo.to_file("ghg_state.shp")

/tmp/ipykernel_3805/3124395807.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  ghgstates_geo.to_file("ghg_state.shp")
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Effective State' to 'Effective'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Emissions' to 'Total Emis'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Direct Emissions' to 'Total Dire'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Supplier Emissions' to 'Total Supp'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Direct Point Emitters' to 'Direct Poi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Onshore Oil & Gas Prod.' to 'Onshore Oi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Gathering & Boosting' to 'Gathering'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Transmission Pipelines' to 'Transmissi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'LDC - Direct Emissions' to 'LDC - Dire'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'SF6 from Elec. Equip.' to 'SF6 from E'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Coal-based liquid fuel production' to 'GHG Quanti'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Produced' to 'GHG Quan_1'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Imported' to 'GHG Quan_2'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Exported' to 'GHG Quan_3'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Natural Gas Supply' to 'GHG Quan_4'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Natural Gas Liquids Supply' to 'GHG Quan_5'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with CO2 Supply' to 'GHG Quan_6'
  ogr_write(

County

In [ ]:
ghg_county = pandas.read_csv("https://github.com/edgi-govdata-archiving/GHG-CDP/raw/refs/heads/main/output_files/aggregated_emissions_by_county.csv")

In [ ]:
import requests
import zipfile
import io

url = "https://www2.census.gov/geo/tiger/TIGER2025/COUNTY/tl_2025_us_county.zip" #Have to use 2020 here because https://www.zip-codes.com/connecticut-change-to-planning-regions.asp
#GHGRP still reported CT County names with 2023 data. Theoretically, we could/should use facility address to map CT emissions to the correct planning region.

# Download
r = requests.get(url)

# Extract
with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    z.extractall("county_shapefile")

In [ ]:
counties = geopandas.read_file("county_shapefile/tl_2025_us_county.shp")

In [ ]:
ghg_county

,STATE,COUNTYNAME_cleaned,County_FIPS,Year,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,LDC - Direct Emissions,SF6 from Elec. Equip.,GHG Quantity Associated with Coal-based liquid fuel production,GHG Quantity Associated with Petroleum Products Produced,GHG Quantity Associated with Petroleum Products Imported,GHG Quantity Associated with Petroleum Products Exported,GHG Quantity Associated with Natural Gas Supply,GHG Quantity Associated with Natural Gas Liquids Supply,GHG Quantity Associated with CO2 Supply
0,AL,Autauga,1001,2010,2982136.634,0.0,2982136.634,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AL,Autauga,1001,2011,4491863.358,0.0,4491863.358,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AL,Autauga,1001,2012,6447401.892,0.0,6447401.892,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AL,Autauga,1001,2013,5530155.518,0.0,5530155.518,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AL,Autauga,1001,2014,5388098.432,0.0,5388098.432,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45103,PR,Yauco,72153,2019,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45104,PR,Yauco,72153,2020,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45105,PR,Yauco,72153,2021,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45106,PR,Yauco,72153,2022,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45107,PR,Yauco,72153,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
counties

,STATEFP,COUNTYFP,COUNTYNS,GEOID,GEOIDFQ,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,40,075,01101825,40075,0500000US40075,Kiowa,Kiowa County,06,H1,G4020,None,None,None,A,2629039892,40296743,+34.9214893,-098.9816168,"POLYGON ((-98.95506 35.11643, -98.94903 35.116..."
1,46,079,01265776,46079,0500000US46079,Lake,Lake County,06,H1,G4020,None,None,None,A,1457916151,31746795,+44.0284497,-097.1232229,"POLYGON ((-96.88886 43.9353, -96.88886 43.9351..."
2,37,033,01008542,37033,0500000US37033,Caswell,Caswell County,06,H1,G4020,None,None,None,A,1102042927,8293623,+36.3943252,-079.3396193,"POLYGON ((-79.14343 36.4422, -79.14345 36.4418..."
3,48,377,01383974,48377,0500000US48377,Presidio,Presidio County,06,H1,G4020,None,None,None,A,9985057447,1773188,+30.0058912,-104.2616192,"POLYGON ((-104.98078 30.62552, -104.98073 30.6..."
4,39,057,01074041,39057,0500000US39057,Greene,Greene County,06,H1,G4020,212,19430,None,A,1071302625,6798109,+39.6874785,-083.8948943,"POLYGON ((-84.10668 39.68891, -84.10662 39.689..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3230,53,065,01531930,53065,0500000US53065,Stevens,Stevens County,06,H1,G4020,518,44060,None,A,6415666347,162933467,+48.3887277,-117.8544548,"POLYGON ((-117.86678 47.84506, -117.8669 47.84..."
3231,19,177,00465277,19177,0500000US19177,Van Buren,Van Buren County,06,H1,G4020,None,None,None,A,1255605674,14880499,+40.7541168,-091.9529430,"POLYGON ((-92.17907 40.89972, -92.17704 40.899..."
3232,31,073,00835858,31073,0500000US31073,Gosper,Gosper County,06,H1,G4020,None,30420,None,A,1186729973,11718014,+40.5090947,-099.8232058,"POLYGON ((-99.98139 40.62501, -99.9814 40.6269..."
3233,28,095,00695771,28095,0500000US28095,Monroe,Monroe County,06,H1,G4020,None,None,None,A,1981673393,17953924,+33.8900295,-088.4850379,"POLYGON ((-88.22909 33.89194, -88.2291 33.8918..."
3234,12,033,00295737,12033,0500000US12033,Escambia,Escambia County,06,H1,G4020,None,37860,None,A,1701617702,1213958859,+30.5299979,-087.3203222,"POLYGON ((-87.63487 30.86634, -87.63485 30.866..."

In [ ]:
ghg_county_2023 = ghg_county[ghg_county["Year"] == 2023]

In [ ]:
ghg_county_2023

,STATE,COUNTYNAME_cleaned,County_FIPS,Year,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,LDC - Direct Emissions,SF6 from Elec. Equip.,GHG Quantity Associated with Coal-based liquid fuel production,GHG Quantity Associated with Petroleum Products Produced,GHG Quantity Associated with Petroleum Products Imported,GHG Quantity Associated with Petroleum Products Exported,GHG Quantity Associated with Natural Gas Supply,GHG Quantity Associated with Natural Gas Liquids Supply,GHG Quantity Associated with CO2 Supply
13,AL,Autauga,1001,2023,5813957.188,0.0,5813957.188,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,AL,Baldwin,1003,2023,259617.750,40563.5,259617.750,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40563.5,0.0,0.0
41,AL,Barbour,1005,2023,6546.276,0.0,6546.276,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,AL,Bibb,1007,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69,AL,Blount,1009,2023,46672.826,0.0,46672.826,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45051,PR,Vega Baja,72145,2023,26031.806,0.0,26031.806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45065,PR,Vieques,72147,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45079,PR,Villalba,72149,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45093,PR,Yabucoa,72151,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45107,PR,Yauco,72153,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
ghg_county_2023["County_FIPS"] = ghg_county_2023["County_FIPS"].astype(str)

/tmp/ipykernel_7418/2630546949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ghg_county_2023["County_FIPS"] = ghg_county_2023["County_FIPS"].astype(str)

In [ ]:
#Fix leading 0s
ghg_county_2023['County_FIPS'] = ghg_county_2023['County_FIPS'].str.zfill(5)

/tmp/ipykernel_7418/2994092177.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ghg_county_2023['County_FIPS'] = ghg_county_2023['County_FIPS'].str.zfill(5)

In [ ]:
ghg_county_2023[ghg_county_2023["COUNTYNAME_cleaned"] == "Fairfield"]["County_FIPS"]

28951    39045
32731    45039
Name: County_FIPS, dtype: object

In [ ]:
ghg_county_2023

,STATE,COUNTYNAME_cleaned,County_FIPS,Year,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,LDC - Direct Emissions,SF6 from Elec. Equip.,GHG Quantity Associated with Coal-based liquid fuel production,GHG Quantity Associated with Petroleum Products Produced,GHG Quantity Associated with Petroleum Products Imported,GHG Quantity Associated with Petroleum Products Exported,GHG Quantity Associated with Natural Gas Supply,GHG Quantity Associated with Natural Gas Liquids Supply,GHG Quantity Associated with CO2 Supply
13,AL,Autauga,01001,2023,5813957.188,0.0,5813957.188,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,AL,Baldwin,01003,2023,259617.750,40563.5,259617.750,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40563.5,0.0,0.0
41,AL,Barbour,01005,2023,6546.276,0.0,6546.276,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,AL,Bibb,01007,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69,AL,Blount,01009,2023,46672.826,0.0,46672.826,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45051,PR,Vega Baja,72145,2023,26031.806,0.0,26031.806,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45065,PR,Vieques,72147,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45079,PR,Villalba,72149,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45093,PR,Yabucoa,72151,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45107,PR,Yauco,72153,2023,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
ghgcounty_geo = pandas.merge(ghg_county_2023, counties, left_on="County_FIPS", right_on="GEOID")

In [ ]:
ghgcounty_geo

,STATE,COUNTYNAME_cleaned,County_FIPS,Year,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,...,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,AL,Autauga,01001,2023,5813957.188,0.0,5813957.188,0.0,0.0,0.0,...,G4020,388,33860,None,A,1539631460,25677536,+32.5322367,-086.6464395,"POLYGON ((-86.58826 32.36775, -86.58834 32.367..."
1,AL,Baldwin,01003,2023,259617.750,40563.5,259617.750,0.0,0.0,0.0,...,G4020,380,19300,None,A,4117933903,1132678359,+30.6592183,-087.7460666,"POLYGON ((-87.97692 31.08658, -87.97688 31.087..."
2,AL,Barbour,01005,2023,6546.276,0.0,6546.276,0.0,0.0,0.0,...,G4020,None,21640,None,A,2292160152,50523213,+31.8702526,-085.4051028,"POLYGON ((-85.41585 31.68164, -85.41619 31.677..."
3,AL,Bibb,01007,2023,0.000,0.0,0.000,0.0,0.0,0.0,...,G4020,142,13820,None,A,1612188713,9572302,+33.0158929,-087.1271475,"POLYGON ((-86.87657 33.01891, -86.87657 33.018..."
4,AL,Blount,01009,2023,46672.826,0.0,46672.826,0.0,0.0,0.0,...,G4020,142,13820,None,A,1670296790,14822589,+33.9773575,-086.5664400,"POLYGON ((-86.56421 33.80194, -86.56556 33.801..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,PR,Vega Baja,72145,2023,26031.806,0.0,26031.806,0.0,0.0,0.0,...,G4020,490,41980,None,A,118748575,57824098,+18.4551279,-066.3978832,"POLYGON ((-66.34974 18.48935, -66.34974 18.489..."
3218,PR,Vieques,72147,2023,0.000,0.0,0.000,0.0,0.0,0.0,...,G4020,None,None,None,A,131541387,552192821,+18.1254180,-065.4324740,"POLYGON ((-65.63097 18.12302, -65.63095 18.123..."
3219,PR,Villalba,72149,2023,0.000,0.0,0.000,0.0,0.0,0.0,...,G4020,434,38660,None,A,92200653,3595301,+18.1307185,-066.4722435,"POLYGON ((-66.49633 18.16708, -66.49588 18.167..."
3220,PR,Yabucoa,72151,2023,0.000,0.0,0.000,0.0,0.0,0.0,...,G4020,490,41980,None,A,143005193,72592515,+18.0598590,-065.8598696,"POLYGON ((-65.7969 18.06982, -65.79683 18.0698..."
3221,PR,Yauco,72153,2023,0.000,0.0,0.000,0.0,0.0,0.0,...,G4020,434,38660,None,A,175436930,1623306,+18.0856688,-066.8579009,"POLYGON ((-66.82399 18.048, -66.82372 18.04787..."

In [ ]:
missing_items = ghg_county_2023[~ghg_county_2023['County_FIPS'].isin(ghgcounty_geo['County_FIPS'])]
missing_items

Empty DataFrame
Columns: [STATE, COUNTYNAME_cleaned, County_FIPS, Year, Total Direct Emissions, Total Supplier Emissions, Direct Point Emitters, Onshore Oil & Gas Prod., Gathering & Boosting, Transmission Pipelines, LDC - Direct Emissions, SF6 from Elec. Equip., GHG Quantity Associated with Coal-based liquid fuel production, GHG Quantity Associated with Petroleum Products Produced, GHG Quantity Associated with Petroleum Products Imported, GHG Quantity Associated with Petroleum Products Exported, GHG Quantity Associated with Natural Gas Supply, GHG Quantity Associated with Natural Gas Liquids Supply, GHG Quantity Associated with CO2 Supply ]
Index: []

In [ ]:
missing_items_2 = counties[~counties['GEOID'].isin(ghg_county_2023['County_FIPS'])]
missing_items_2

,STATEFP,COUNTYFP,COUNTYNS,GEOID,GEOIDFQ,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
220,78,020,02378249,78020,0500000US78020,St. John,St. John Island,10,H4,G4020,None,None,None,N,50998058,186670411,+18.3304347,-064.7352610,"POLYGON ((-64.84373 18.39371, -64.84136 18.393..."
226,78,030,02378250,78030,0500000US78030,St. Thomas,St. Thomas Island,10,H4,G4020,None,None,None,N,81108881,717920921,+18.3392359,-064.9500433,"POLYGON ((-65.15388 18.28114, -65.15364 18.293..."
343,60,040,01805244,60040,0500000US60040,Swains Island,Swains Island,00,H4,G4020,None,None,None,N,2432605,149170816,-11.0544359,-171.0690136,"POLYGON ((-171.14118 -11.04661, -171.14116 -11..."
449,66,010,01802705,66010,0500000US66010,Guam,Guam,00,H4,G4020,None,None,None,F,543555846,934337452,+13.4382885,+144.7729494,"POLYGON ((144.56343 13.44806, 144.56357 13.450..."
489,69,100,01805246,69100,0500000US69100,Rota,Rota Municipality,12,H1,G4020,None,None,None,A,85096796,539092797,+14.1524934,+145.2129037,"POLYGON ((145.05897 14.125, 145.06302 14.1379,..."
1254,69,110,01805247,69110,0500000US69110,Saipan,Saipan Municipality,12,H1,G4020,None,None,None,A,118890990,532767361,+15.1980954,+145.7771923,"POLYGON ((145.58774 15.12775, 145.63317 15.135..."
1445,60,020,01805242,60020,0500000US60020,Manu'a,Manu'a District,07,H1,G4020,None,None,None,A,57620993,464238044,-14.2198008,-169.5076973,"POLYGON ((-169.44603 -14.30487, -169.44653 -14..."
1448,69,120,01805248,69120,0500000US69120,Tinian,Tinian Municipality,12,H1,G4020,None,None,None,A,108237606,632893009,+15.0010865,+145.6181702,"POLYGON ((145.46822 14.85334, 145.4702 14.8648..."
2013,78,010,02378248,78010,0500000US78010,St. Croix,St. Croix Island,10,H4,G4020,None,None,None,N,215914976,645644854,+17.7352317,-064.7466437,"POLYGON ((-64.95671 17.67898, -64.95638 17.683..."
2061,60,050,01805241,60050,0500000US60050,Western,Western District,07,H1,G4020,None,None,None,A,72498514,196726219,-14.3348500,-170.7841050,"POLYGON ((-170.89029 -14.31719, -170.88846 -14..."
2339,60,030,01805243,60030,0500000US60030,Rose Island,Rose Island,00,H4,G4020,None,None,None,N,82093,147383994,-14.5365298,-168.1512918,"POLYGON ((-168.22527 -14.53591, -168.22453 -14..."
2715,60,010,01805240,60010,0500000US60010,Eastern,Eastern District,07,H1,G4020,None,None,None,A,65124865,349724678,-14.2681144,-170.6257058,"POLYGON ((-170.53809 -14.33613, -170.54848 -14..."
2826,69,085,01805245,69085,0500000US69085,Northern Islands,Northern Islands Municipality,12,H1,G4020,None,None,None,B,160067128,2939499290,+18.1163650,+145.7667015,"MULTIPOLYGON (((145.74666 17.59937, 145.74742 ..."

In [ ]:
ghgcounty_geo = geopandas.GeoDataFrame(ghgcounty_geo, geometry = "geometry")

In [ ]:
ghgcounty_geo.to_file("ghg_county_2023.shp")

/tmp/ipykernel_7418/4189829977.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  ghgcounty_geo.to_file("ghg_county_2023.shp")
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'COUNTYNAME_cleaned' to 'COUNTYNAME'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'County_FIPS' to 'County_FIP'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Direct Emissions' to 'Total Dire'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Supplier Emissions' to 'Total Supp'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Direct Point Emitters' to 'Direct Poi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Onshore Oil & Gas Prod.' to 'Onshore Oi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Gathering & Boosting' to 'Gathering'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Transmission Pipelines' to 'Transmissi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'LDC - Direct Emissions' to 'LDC - Dire'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'SF6 from Elec. Equip.' to 'SF6 from E'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Coal-based liquid fuel production' to 'GHG Quanti'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Produced' to 'GHG Quan_1'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Imported' to 'GHG Quan_2'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Exported' to 'GHG Quan_3'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Natural Gas Supply' to 'GHG Quan_4'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Natural Gas Liquids Supply' to 'GHG Quan_5'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with CO2 Supply ' to 'GHG Quan_6'
  ogr_write(

CD

In [ ]:
ghg_cd = pandas.read_csv("https://github.com/edgi-govdata-archiving/GHG-CDP/raw/refs/heads/main/output_files/aggregated_emissions_by_cd.csv")

In [ ]:
ghg_cd

,DISTRICTID,Year,Total Emissions,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,LDC - Direct Emissions,...,GHG Quantity Associated with Coal-based liquid fuel production,GHG Quantity Associated with Petroleum Products Produced,GHG Quantity Associated with Petroleum Products Imported,GHG Quantity Associated with Petroleum Products Exported,GHG Quantity Associated with Natural Gas Supply,GHG Quantity Associated with Natural Gas Liquids Supply,GHG Quantity Associated with CO2 Supply,Representative_Name,Representative_Last_Name,Representative_Party
0,101,2010,1.869101e+07,1.582564e+07,2.865372e+06,1.582564e+07,0.0,0.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,2.195013e+06,670359.5,0.0,Barry Moore,Moore,Republican
1,101,2011,1.646752e+07,1.394090e+07,2.526624e+06,1.394090e+07,0.0,0.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,1.925175e+06,601449.1,0.0,Barry Moore,Moore,Republican
2,101,2012,2.943373e+07,1.513857e+07,1.429516e+07,1.513857e+07,0.0,0.0,0.0,0.0,...,0.0,1.154084e+07,0.0,0.0,2.228206e+06,526112.7,0.0,Barry Moore,Moore,Republican
3,101,2013,3.022357e+07,1.541616e+07,1.480741e+07,1.541616e+07,0.0,0.0,0.0,0.0,...,0.0,1.203272e+07,0.0,0.0,2.249195e+06,525494.6,0.0,Barry Moore,Moore,Republican
4,101,2014,3.120519e+07,1.570118e+07,1.550401e+07,1.570118e+07,0.0,0.0,0.0,0.0,...,0.0,1.276734e+07,0.0,0.0,2.300522e+06,436145.4,0.0,Barry Moore,Moore,Republican
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6169,7898,2019,7.859779e+05,7.859779e+05,0.000000e+00,7.859779e+05,0.0,0.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,Stacey E. Plaskett,Plaskett,Democrat
6170,7898,2020,2.568699e+06,1.073728e+06,1.494971e+06,1.073728e+06,0.0,0.0,0.0,0.0,...,0.0,1.494971e+06,0.0,0.0,0.000000e+00,0.0,0.0,Stacey E. Plaskett,Plaskett,Democrat
6171,7898,2021,4.942340e+06,1.570238e+06,3.372103e+06,1.570238e+06,0.0,0.0,0.0,0.0,...,0.0,3.372103e+06,0.0,0.0,0.000000e+00,0.0,0.0,Stacey E. Plaskett,Plaskett,Democrat
6172,7898,2022,7.288500e+05,7.288500e+05,0.000000e+00,7.288500e+05,0.0,0.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,Stacey E. Plaskett,Plaskett,Democrat
6173,7898,2023,5.811637e+05,5.811637e+05,0.000000e+00,5.811637e+05,0.0,0.0,0.0,0.0,...,0.0,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.0,Stacey E. Plaskett,Plaskett,Democrat

In [ ]:
ghg_cd_2023 = ghg_cd[ghg_cd["Year"] == 2023]

In [ ]:
ghg_cd_2023["DISTRICTID"] = ghg_cd_2023["DISTRICTID"].astype(str)

/tmp/ipykernel_60512/1608296185.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ghg_cd_2023["DISTRICTID"] = ghg_cd_2023["DISTRICTID"].astype(str)

In [ ]:
#Fix leading 0s
ghg_cd_2023['DISTRICTID'] = ghg_cd_2023['DISTRICTID'].str.zfill(4)

/tmp/ipykernel_60512/181181863.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ghg_cd_2023['DISTRICTID'] = ghg_cd_2023['DISTRICTID'].str.zfill(4)

In [ ]:
ghg_cd_2023

,DISTRICTID,Year,Total Emissions,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,LDC - Direct Emissions,...,GHG Quantity Associated with Coal-based liquid fuel production,GHG Quantity Associated with Petroleum Products Produced,GHG Quantity Associated with Petroleum Products Imported,GHG Quantity Associated with Petroleum Products Exported,GHG Quantity Associated with Natural Gas Supply,GHG Quantity Associated with Natural Gas Liquids Supply,GHG Quantity Associated with CO2 Supply,Representative_Name,Representative_Last_Name,Representative_Party
13,0101,2023,2.812154e+07,1.173925e+07,1.638229e+07,1.173764e+07,0.0,0.0,0.0,0.00,...,0.0,1.182564e+07,0.0,0.0,2828049.5,1728605.8,0.0,Barry Moore,Moore,Republican
27,0102,2023,8.044804e+06,4.283164e+06,3.761640e+06,4.269157e+06,0.0,0.0,0.0,14007.15,...,0.0,0.000000e+00,0.0,0.0,3761639.7,0.0,0.0,Shomari Figures,Figures,Democrat
41,0103,2023,8.968936e+06,8.781237e+06,1.876991e+05,8.781237e+06,0.0,0.0,0.0,0.00,...,0.0,0.000000e+00,0.0,0.0,187699.1,0.0,0.0,Mike Rogers,Rogers,Republican
55,0104,2023,3.233845e+06,1.783754e+06,1.450091e+06,1.783754e+06,0.0,0.0,0.0,0.00,...,0.0,0.000000e+00,0.0,0.0,1450091.0,0.0,0.0,Robert B. Aderholt,Aderholt,Republican
69,0105,2023,7.249692e+06,6.472619e+06,7.770733e+05,6.465083e+06,0.0,0.0,0.0,7535.80,...,0.0,0.000000e+00,0.0,0.0,777073.3,0.0,0.0,Dale W. Strong,Strong,Republican
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6117,6098,2023,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.00,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,Aumua Amata Coleman Radewagen,Radewagen,Republican
6131,6698,2023,1.304859e+06,1.304859e+06,0.000000e+00,1.304859e+06,0.0,0.0,0.0,0.00,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,James C. Moylan,Moylan,Republican
6145,6998,2023,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.00,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,Kimberlyn King-Hinds,King-Hinds,Republican
6159,7298,2023,1.380342e+07,1.380342e+07,0.000000e+00,1.372998e+07,0.0,0.0,0.0,0.00,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,Pablo José Hernández,Hernández,Democrat
6173,7898,2023,5.811637e+05,5.811637e+05,0.000000e+00,5.811637e+05,0.0,0.0,0.0,0.00,...,0.0,0.000000e+00,0.0,0.0,0.0,0.0,0.0,Stacey E. Plaskett,Plaskett,Democrat

In [ ]:
cd = geopandas.read_file("/content/drive/Shareddrives/EDGI - Shared NEW/12_Environmental_Enforcement_Watch/09_Data/cds_119th.geojson")

In [ ]:
cd

,OBJECTID,DISTRICTID,STFIPS,CDFIPS,STATE_ABBR,NAME,LAST_NAME,PARTY,SQMI,STATE_NAME,Shape__Area,Shape__Length,geometry
0,1,0101,01,01,AL,Barry Moore,Moore,Republican,7335.82,Alabama,1.796181,22.880109,"MULTIPOLYGON (((-88.07826 30.25212, -88.0783 3..."
1,2,0102,01,02,AL,Shomari Figures,Figures,Democrat,9551.34,Alabama,2.354936,15.281218,"MULTIPOLYGON (((-88.02664 30.75584, -88.02681 ..."
2,3,0103,01,03,AL,Mike Rogers,Rogers,Republican,6870.28,Alabama,1.724848,7.749122,"POLYGON ((-85.51361 34.52382, -85.51304 34.521..."
3,4,0104,01,04,AL,Robert B. Aderholt,Aderholt,Republican,8853.57,Alabama,2.240823,11.966234,"POLYGON ((-87.42457 35.00243, -87.42461 35.002..."
4,5,0105,01,05,AL,Dale W. Strong,Strong,Republican,4066.66,Alabama,1.036197,5.943363,"MULTIPOLYGON (((-86.14981 34.53363, -86.14981 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,437,6098,60,98,AS,Aumua Amata Coleman Radewagen,Radewagen,Republican,77.99,American Samoa,0.016917,1.825067,"MULTIPOLYGON (((-168.14437 -14.54849, -168.144..."
437,438,6698,66,98,GU,James C. Moylan,Moylan,Republican,216.46,Guam,0.046796,1.433019,"MULTIPOLYGON (((144.64593 13.23419, 144.64443 ..."
438,439,6998,69,98,MP,Kimberlyn King-Hinds,King-Hinds,Republican,184.46,Northern Mariana,0.040336,3.252966,"MULTIPOLYGON (((145.28434 14.17537, 145.28404 ..."
439,440,7298,72,98,PR,Pablo José Hernández,Hernández,Democrat,3486.40,Puerto Rico,0.771305,6.861809,"MULTIPOLYGON (((-66.52681 17.88475, -66.52824 ..."
440,441,7898,78,98,VI,Stacey E. Plaskett,Plaskett,Democrat,137.41,Virgin Islands,0.030357,2.991084,"MULTIPOLYGON (((-64.76102 17.68242, -64.76133 ..."

In [ ]:
cd["DISTRICTID"] = cd["DISTRICTID"].astype(str)

In [ ]:
cd

,OBJECTID,DISTRICTID,STFIPS,CDFIPS,STATE_ABBR,NAME,LAST_NAME,PARTY,SQMI,STATE_NAME,Shape__Area,Shape__Length,geometry
0,1,0101,01,01,AL,Barry Moore,Moore,Republican,7335.82,Alabama,1.796181,22.880109,"MULTIPOLYGON (((-88.07826 30.25212, -88.0783 3..."
1,2,0102,01,02,AL,Shomari Figures,Figures,Democrat,9551.34,Alabama,2.354936,15.281218,"MULTIPOLYGON (((-88.02664 30.75584, -88.02681 ..."
2,3,0103,01,03,AL,Mike Rogers,Rogers,Republican,6870.28,Alabama,1.724848,7.749122,"POLYGON ((-85.51361 34.52382, -85.51304 34.521..."
3,4,0104,01,04,AL,Robert B. Aderholt,Aderholt,Republican,8853.57,Alabama,2.240823,11.966234,"POLYGON ((-87.42457 35.00243, -87.42461 35.002..."
4,5,0105,01,05,AL,Dale W. Strong,Strong,Republican,4066.66,Alabama,1.036197,5.943363,"MULTIPOLYGON (((-86.14981 34.53363, -86.14981 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,437,6098,60,98,AS,Aumua Amata Coleman Radewagen,Radewagen,Republican,77.99,American Samoa,0.016917,1.825067,"MULTIPOLYGON (((-168.14437 -14.54849, -168.144..."
437,438,6698,66,98,GU,James C. Moylan,Moylan,Republican,216.46,Guam,0.046796,1.433019,"MULTIPOLYGON (((144.64593 13.23419, 144.64443 ..."
438,439,6998,69,98,MP,Kimberlyn King-Hinds,King-Hinds,Republican,184.46,Northern Mariana,0.040336,3.252966,"MULTIPOLYGON (((145.28434 14.17537, 145.28404 ..."
439,440,7298,72,98,PR,Pablo José Hernández,Hernández,Democrat,3486.40,Puerto Rico,0.771305,6.861809,"MULTIPOLYGON (((-66.52681 17.88475, -66.52824 ..."
440,441,7898,78,98,VI,Stacey E. Plaskett,Plaskett,Democrat,137.41,Virgin Islands,0.030357,2.991084,"MULTIPOLYGON (((-64.76102 17.68242, -64.76133 ..."

In [ ]:
ghgcd_geo = ghg_cd_2023.merge(cd, on="DISTRICTID")

In [ ]:
ghgcd_geo

,DISTRICTID,Year,Total Emissions,Total Direct Emissions,Total Supplier Emissions,Direct Point Emitters,Onshore Oil & Gas Prod.,Gathering & Boosting,Transmission Pipelines,LDC - Direct Emissions,...,CDFIPS,STATE_ABBR,NAME,LAST_NAME,PARTY,SQMI,STATE_NAME,Shape__Area,Shape__Length,geometry
0,0101,2023,2.812154e+07,1.173925e+07,1.638229e+07,1.173764e+07,0.0,0.0,0.0,0.00,...,01,AL,Barry Moore,Moore,Republican,7335.82,Alabama,1.796181,22.880109,"MULTIPOLYGON (((-88.07826 30.25212, -88.0783 3..."
1,0102,2023,8.044804e+06,4.283164e+06,3.761640e+06,4.269157e+06,0.0,0.0,0.0,14007.15,...,02,AL,Shomari Figures,Figures,Democrat,9551.34,Alabama,2.354936,15.281218,"MULTIPOLYGON (((-88.02664 30.75584, -88.02681 ..."
2,0103,2023,8.968936e+06,8.781237e+06,1.876991e+05,8.781237e+06,0.0,0.0,0.0,0.00,...,03,AL,Mike Rogers,Rogers,Republican,6870.28,Alabama,1.724848,7.749122,"POLYGON ((-85.51361 34.52382, -85.51304 34.521..."
3,0104,2023,3.233845e+06,1.783754e+06,1.450091e+06,1.783754e+06,0.0,0.0,0.0,0.00,...,04,AL,Robert B. Aderholt,Aderholt,Republican,8853.57,Alabama,2.240823,11.966234,"POLYGON ((-87.42457 35.00243, -87.42461 35.002..."
4,0105,2023,7.249692e+06,6.472619e+06,7.770733e+05,6.465083e+06,0.0,0.0,0.0,7535.80,...,05,AL,Dale W. Strong,Strong,Republican,4066.66,Alabama,1.036197,5.943363,"MULTIPOLYGON (((-86.14981 34.53363, -86.14981 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436,6098,2023,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.00,...,98,AS,Aumua Amata Coleman Radewagen,Radewagen,Republican,77.99,American Samoa,0.016917,1.825067,"MULTIPOLYGON (((-168.14437 -14.54849, -168.144..."
437,6698,2023,1.304859e+06,1.304859e+06,0.000000e+00,1.304859e+06,0.0,0.0,0.0,0.00,...,98,GU,James C. Moylan,Moylan,Republican,216.46,Guam,0.046796,1.433019,"MULTIPOLYGON (((144.64593 13.23419, 144.64443 ..."
438,6998,2023,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.00,...,98,MP,Kimberlyn King-Hinds,King-Hinds,Republican,184.46,Northern Mariana,0.040336,3.252966,"MULTIPOLYGON (((145.28434 14.17537, 145.28404 ..."
439,7298,2023,1.380342e+07,1.380342e+07,0.000000e+00,1.372998e+07,0.0,0.0,0.0,0.00,...,98,PR,Pablo José Hernández,Hernández,Democrat,3486.40,Puerto Rico,0.771305,6.861809,"MULTIPOLYGON (((-66.52681 17.88475, -66.52824 ..."
440,7898,2023,5.811637e+05,5.811637e+05,0.000000e+00,5.811637e+05,0.0,0.0,0.0,0.00,...,98,VI,Stacey E. Plaskett,Plaskett,Democrat,137.41,Virgin Islands,0.030357,2.991084,"MULTIPOLYGON (((-64.76102 17.68242, -64.76133 ..."

In [ ]:
ghgcd_geo = geopandas.GeoDataFrame(ghgcd_geo, geometry = "geometry")

In [ ]:
ghgcd_geo.to_file("ghg_cd_2023.shp")

/tmp/ipykernel_60512/2183025381.py:1: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  ghgcd_geo.to_file("ghg_cd_2023.shp")
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Emissions' to 'Total Emis'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Direct Emissions' to 'Total Dire'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Total Supplier Emissions' to 'Total Supp'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Direct Point Emitters' to 'Direct Poi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Onshore Oil & Gas Prod.' to 'Onshore Oi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Gathering & Boosting' to 'Gathering'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Transmission Pipelines' to 'Transmissi'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'LDC - Direct Emissions' to 'LDC - Dire'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'SF6 from Elec. Equip.' to 'SF6 from E'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Coal-based liquid fuel production' to 'GHG Quanti'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Produced' to 'GHG Quan_1'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Imported' to 'GHG Quan_2'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Petroleum Products Exported' to 'GHG Quan_3'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Natural Gas Supply' to 'GHG Quan_4'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with Natural Gas Liquids Supply' to 'GHG Quan_5'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'GHG Quantity Associated with CO2 Supply ' to 'GHG Quan_6'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Representative_Name' to 'Representa'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Representative_Last_Name' to 'Represen_1'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Representative_Party' to 'Represen_2'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Shape__Area' to 'Shape__Are'
  ogr_write(
/usr/local/lib/python3.12/dist-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'Shape__Length' to 'Shape__Len'
  ogr_write(

Facilities

In [ ]:
ghg_fac = pandas.read_csv("https://github.com/edgi-govdata-archiving/GHG-CDP/raw/refs/heads/main/output_files/aggregated_emissions_by_facility_with_metadata_2.csv")

In [ ]:
ghg_fac_2023 = ghg_fac[ghg_fac["Year"] == 2023]

In [ ]:
ghg_fac_2023.to_csv("ghg_fac_2023_2.csv")